### ISSUE TITLE
Isn't it supposed to be RELEASE?

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc-check-action#3]
We agreed on RELEASE as the tag for the current release, but I see LATEST [here](https://github.com/cljdoc/cljdoc-check-action/blob/3bd9b4b70a30d951e332e877af5227e8fc48d277/action.yml#L19-L22).

**Comment by lread** [comment]
Ah. That's for the lib under test?
But, maybe this should be RELEASE [here](https://github.com/cljdoc/cljdoc-check-action/blob/3bd9b4b70a30d951e332e877af5227e8fc48d277/Dockerfile#L5) so that we always use the current cljdoc-analyzer release.

**Comment by holyjak** [comment]
A possible problem with RELEASE is that it could start to break when some incompatible change is introduced. And then you are left wondering why cljdoc checks for your lib suddenly started failing and search your recent changes in vain. But perhaps the risk of that is low and outweighted of the benefit of latest and more de-bugged cljdoc? What do you think?

**Comment by lread** [comment]
Ya, cljdoc uses the RELEASE version of cljdoc-analyzer, so we'd be matching prod, so worth it.
